### ISSUE TITLE
Missing "Cr" atom

### ISSUE THREAD

**Issue by mrakitin** [2019-ncovgroup/DataCrunching#5]
Reported via email by @ochubar.

### Example to reproduce:
```
[O-][51Cr](=O)(=O)[O-] DB-10072
```

### Output:
```
autogrid4: ERROR:  unknown ligand atom type Cr
add parameters for it to the parameter library first!


autodock4: ERROR:  Unknown ligand atom type "Cr"; add parameters for it to the parameter library first!
autodock4: FATAL ERROR: autodock4: ERROR:  Unknown ligand atom type "Cr"; add parameters for it to the parameter library first!

autodock4: Unsuccessful Completion.
```
The atom is not in http://autodock.scripps.edu/resources/parameters/AD4_parameters.dat/view or https://github.com/2019-ncovgroup/DataCrunching/blob/master/Autodock4-enhancement/AD4_parameters.dat.

**Comment by mrakitin** [comment]
The atom was added via https://github.com/2019-ncovgroup/DataCrunching/commit/35cabeecb19ae016428bce680e66bd545b422994 and https://github.com/2019-ncovgroup/DataCrunching/commit/2722f49f9f33a8cb13ffe6504c5d6ba6eac722bc.

@hjjvandam, I observe a few warning messages:
```
Unable to assign MAP type to atom Cr
Sorry, there are no Gasteiger parameters available for atom DB-10072:default:UNL1:CR
Unable to assign XYZ type to atom Cr
Unable to assign HYB type to atom Cr
Unable to assign HYB type to atom Cr
Unable to assign HYB type to atom Cr
Unable to assign HYB type to atom Cr
Unable to assign XYZ type to atom Cr
Unable to assign HYB type to atom Cr
Unable to assign HYB type to atom Cr
Unable to assign HYB type to atom Cr
Unable to assign HYB type to atom Cr
Unable to assign XYZ type to atom Cr
Unable to assign HYB type to atom Cr
Unable to assign HYB type to atom Cr
Unable to assign HYB type to atom Cr
Unable to assign HYB type to atom Cr
```
but the simulations proceed. Is it a problem?

**Comment by hjjvandam** [comment]
Hi Maksim,

I am not sure how much of a problem this is. The Gasteiger parameters are used in the algorithm that generates partial charges for the atoms. So I assume that Cr will get a charge of 0.0. Other than that I don’t know what the other warning messages mean.

Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov<mailto:hvandam@bnl.gov>
Brookhaven National Laboratory

**Comment by mrakitin** [comment]
I see, thanks.
